### PR TITLE
Update to FFmpeg 2.7.2.

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
It's working for linux amd64 and armv7

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Deleting all the Windows binaries isn't really a good option here.

That's almost the entire point of this repo, aside from speeding up Travis linux builds, Linux users could just compile it themselves.  It's a pain to compile on Windows.

-[Unknown]

**Comment by sergiobenrocha2** [comment]
Ops, sorry.

**Comment by hrydgard** [comment]
This version of FFMPEG is reasonably new and builds nicely with VS 2015. Let's use it.

Sorry for the delay @sergiobenrocha2 .

**Comment by xsacha** [comment]
I suppose I need to provide Symbian and BB binaries for this too.
I think the BB multi-core fix is also required so I'll test that out on a device.

**Comment by hrydgard** [comment]
@xsacha I don't think you actually need to, because not much seems to have changed on the ffmpeg side. That said, always good to be up to date, but it's not super urgent for those platforms.

**Pull request merged**
