### PR TITLE
Add mpeg4 on Linux. Update Linux x86_64 libs and headers, rebuild x86 with mpeg4 support.

### PR DESCRIPTION
**Pull request by hcorion**
These were generated on Arch Linux.
I added the mpeg4 support because we were having some troubles with RPCS3 trying to use mpeg4.
```
$ gcc --version
gcc (GCC) 7.1.1 20170630
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```shell
$ pacman -Ss glibc           
core/glibc 2.25-7 (base) [installed]
    GNU C Library
```

### CODE REVIEW

**Comment by hcorion** [comment]
It's already enabled on Windows, not sure about other platforms

**Comment by unknownbrackets** [comment]
Ah, indeed.  Looks like someone started to refactor but didn't update all the scripts:
https://github.com/hrydgard/ppsspp-ffmpeg/blob/master/shared_options.sh#L26

The list used by other platforms is probably more correct for PPSSPP:
https://github.com/hrydgard/ppsspp-ffmpeg/blob/master/android_x86.sh#L40-L45

So it seems Linux and Mac are the wrong ones, but not sure we really need mjpeg or h263.  Does RPCS3 use any of the other decoders?

-[Unknown]

**Comment by hrydgard** [comment]
Oh, sorry for the delay, I forgot about this pull request.

Thanks unknown. I don't think it matters much if we have mjpeg or h263 unnecessarily, they're probably either small or sharing at least some code with h264..

**Comment by hcorion** [comment]
Also, just FYI, If you try to link these libs with the ld provided in binutils 2.26 (the one currently used in Ubuntu Trusty), it will fail. You need to use a newer binutils for that.

**Comment by unknownbrackets** [comment]
Hmm, not sure - that might be a problem.  I think our travis builds are on Trusty...

-[Unknown]

**Comment by hcorion** [comment]
Yes, I had to hack the RPCS3 travis build by using a non-official binutils version, see: https://github.com/RPCS3/rpcs3/commit/514a98321df1b481bf3d1ffb7ca39a6967a89466

**Comment by hcorion** [comment]
The executables still work, but it's a nasty security problem.

**Pull request merged**
