### PR TITLE
Update ffmpeg version on Windows for VS2015

### PR DESCRIPTION
**Pull request by Bigpet**
So this updates ffmpeg to get a version that compiles in VS2015 (at least the libraries do, we don't compile the command line tool anyway).

I tested whether VS2015 could use the libs compiled with VS2013 and it doesn't (linking the stdlib dynamically or statically doesn't matter, it just doesn't work).

I did update the VS2013 libs to the newer version too and added VS2015 versions in the format "avcodec.v140.lib".

Maybe renaming the VS2013 libs to "avcodec.v120.lib" would allow us to use "avcodec.$(PlatformToolset).lib". I just don't see an easy way to automatically output the right name with the windows_XXX-build.sh scripts. The only thing I came across was the %VisualStudioVersion% environment variable in the VSCommandPrompt which is in the format "12.0", so we would use bash to take that, remove the dot and prefix it with ".v"

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
PPSSPP should use "stable" releases instead random snapshots...

Does 2.7.1 work on windows?

**Comment by xsacha** [comment]
For a long time there was no stable release with ATRAC3+ support. I suppose there is one now.

**Comment by unknownbrackets** [comment]
2.7.1 includes the fairly recent patch to fix ATRAC3+ with GHA phase shifting, afaik.  So yes, could update to that.  Although, iirc, FFmpeg's policy was always "use the latest svn/git version or don't report issues", not sure if that has changed these days...

-[Unknown]

**Comment by sergiobenrocha2** [comment]
With stable release you at least can compare with Arch Linux or Debian Sid, for example (in the case you are using shared libs).

**Comment by xsacha** [comment]
Is there any distro that has a ffmpeg that supports atrac3+ yet?

**Comment by unknownbrackets** [comment]
Well, the one they need was literally released last week.  If that's a reasonable dependency, then it seems like it ought to be fine to use a shared ffmpeg.

-[Unknown]

**Comment by sergiobenrocha2** [comment]
atrac3+ is not enabled in Arch Linux yet? Licensing problem?

**Comment by Bigpet** [comment]
@sergiobenrocha2 sorry for answering so late but yeah both 2.7.1 and 2.7.2 have the VS2015 changes.

Btw. VS2015 is now released. About outputting the right name, I guess we don't need to do the generic  string manipulation, we could just essentially do the bash equivalent to what wxWidgets does: https://github.com/wxWidgets/wxWidgets/blob/master/build/msw/wx_config.props 

But I vaguely remember @hrygard having some objections to carrying around multiple versions for Windows, I just don't remember the details of that conversation or where it took place

**Comment by hrydgard** [comment]
Yeah, we will switch to VS2015 soon and rebuild the ffmpeg libs. Might as well update to latest FFMPEG while at it.

My objection to multiple versions is just that the ffmpeg submodule is already ridiculously large.

**Comment by hrydgard** [comment]
Doing https://github.com/hrydgard/ppsspp-ffmpeg/pull/35 instead.

**Pull request closed without merging**
