### PR TITLE
riscv64 bootstrap

### LINKED ISSUE #62: Unable to build on RISC-V
When attempting to run `./configure` I get the following;

```
root@debian:~/ppsspp/ffmpeg# ./configure
install prefix            /usr/local
source path               .
C compiler                gcc
C library                 glibc
ARCH                      riscv64 (generic)
big-endian                no
runtime cpu detection     yes
debug symbols             yes
strip symbols             yes
optimize for size         no
optimizations             yes
static                    yes
shared                    no
postprocessing support    no
new filter support        yes
network support           yes
threading support         pthreads
safe bitstream reader     yes
SDL support               no
opencl enabled            no
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          no
makeinfo supports HTML    no

Enabled programs:
ffmpeg                  ffprobe

...

License: LGPL version 2.1 or later
Creating config.mak, config.h, and doc/config.texi...
config.h is unchanged
libavutil/avconfig.h is unchanged

WARNING: unknown architecture riscv64
```

### PR DESCRIPTION
**Pull request by archanox**
This fixes #62.

There doesn't seem to be any special RISC-V extensions upstream either, so nothing appeared to be "backportable" as far as I could see.

I'd love to get another set of eyes on this to see if I'm missing anything.

### CODE REVIEW

**Comment by hrydgard** [comment]
Cool.

Just curious, before I merge, have you tested running this, not just compiling it?

**Comment by archanox** [comment]
Short answer, no I haven't tested them. What would be the best way to test these libraries @hrydgard?
In the mean time, I'll run through running the FATE tests from this repo. https://ffmpeg.org/fate.html

**Comment by xsacha** [comment]
To test ffmpeg, just build ffplay and try to play videos with it.

I'd imagine any code in FFMPEG would be cross-architecture. Probably won't be any specific RISC-V hardware being used to optimise performance though. I assume the chip has a video decoder element of it that would be more efficient that decoding on the CPU and there may be effort somewhere to port this in.

**Comment by archanox** [comment]
I've tried to run the fate tests. But unfortunately there's an issue with building them. I didn't check if this is isolated to my changes or RISC-V, but it looks like there's a bit of RISC-V work that should happen upstream.

I'll have another crack at it tomorrow, but I'm not sure if it's worth accepting my partial changes if the work needs to be done upstream as well.

There's changes that I missed in the configure that have not been pushed yet. But again, they probably should come from upstream.

I'm a bit sad the scope of work has increased from "get this old fork to build" to "I gotta work with the FFmpeg folks to get RISC-V officially supported".

**Comment by hrydgard** [comment]
That's not what I meant, I meant have you built a PPSSPP for RISC-V and tested with this? Because that's the only real use case for this forked ffmpeg. Once you have that, I'm happy to merge. Don't care about ffplay etc.

**Comment by unknownbrackets** [comment]
I added a comment to https://github.com/hrydgard/ppsspp/pull/14561 about getting that to link, which might enable you to see if music and videos decode with this.

-[Unknown]

**Comment by archanox** [comment]
> Cool.
> 
> 
> 
> Just curious, before I merge, have you tested running this, not just compiling it?

I've confirmed that these changes are working and running successfully with both audio and video.

**Comment by hrydgard** [comment]
Then I'm happy to merge!

**Comment by archanox** [comment]
Thanks again to @unknownbrackets for his guidance here.

**Pull request merged**
