### PR TITLE
Added ARMv7 Linux ffmpeg, primary for Raspberry Pi

### PR DESCRIPTION
**Pull request by GAMELASTER**
Compiled on Ubuntu with Crosstool for ARMv7 with Hard Floating, works corrrectly in building :-) . Its can help anyone who trying to build PPSSPP too right now for new RPI 2 :-)

### CODE REVIEW

**Comment by hrydgard** [comment]
Seems you forgot to add your modified .sh build script?

**Comment by GAMELASTER** [comment]
Oh, yes, i forgot. I add it, just i must edit script for some informations etc...

**Comment by GAMELASTER** [comment]
Added! :) For trust i checked if it works, its works great!

**Comment by hrydgard** [comment]
So the emulator runs on RPi B+ now? :)

**Comment by GAMELASTER** [comment]
Its only about FFMPEG, build of PPSSPP is right without problem. But still is trouble with SDL (about i writing on issue at PPSSPP repository! .

Anyway, today i downloaded new Commit of PPSSPP and while build i got some errors, so when i comment this im going to send issue with errors. Becouse yesterday's build works good.

Some parameters: This all is only for Raspberry Pi 2 +, becouse only RPI2 got ARMv7 processor, on older has been ARMv6 build needed, but if needed i can do for older RPi's FFMPEG build script and librarys too :)

**Comment by GAMELASTER** [comment]
Okey, i checked all and this form is ready to merge, its really tooks so much long to build FFMPEG libraries so its can help someone :-)

**Pull request merged**
